"""Mock email sender tool."""

from datetime import datetime
from pathlib import Path

from src.config import settings


def send_action_item_email(
    recipient_email: str,
    recipient_name: str,
    action_item: dict,
    meeting_summary: str,
) -> dict:
    """Send a mock action item notification email by writing to a file.

    Args:
        recipient_email: Email address of the recipient.
        recipient_name: Full name of the recipient.
        action_item: Action item dict with description, priority, deadline, context.
        meeting_summary: Summary of the meeting for context.

    Returns:
        Dict with status ("sent"/"failed"), recipient, and timestamp.
    """
    timestamp = datetime.now()
    first_name = recipient_name.split()[0] if recipient_name else "Team Member"

    email_body = f"""Subject: Action Item Assigned: {action_item.get('description', 'N/A')}
To: {recipient_email}
Date: {timestamp.strftime('%Y-%m-%d %H:%M:%S')}

Hi {first_name},

You've been assigned an action item from a recent meeting:

TASK: {action_item.get('description', 'N/A')}
PRIORITY: {action_item.get('priority', 'MEDIUM')}
DEADLINE: {action_item.get('deadline', 'Not specified')}

Context from meeting:
{action_item.get('context', 'N/A')}

Meeting Summary:
{meeting_summary}

Please confirm receipt and update your task tracker.

---
This email was automatically generated by Huddle AI.
"""

    try:
        emails_dir = Path(settings.EMAILS_DIR)
        emails_dir.mkdir(parents=True, exist_ok=True)

        safe_email = recipient_email.replace("@", "_at_")
        ts_str = timestamp.strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_email}_{ts_str}.txt"
        filepath = emails_dir / filename

        filepath.write_text(email_body)

        return {
            "status": "sent",
            "recipient": recipient_email,
            "timestamp": timestamp.isoformat(),
            "file": str(filepath),
        }
    except Exception as e:
        return {
            "status": "failed",
            "recipient": recipient_email,
            "timestamp": timestamp.isoformat(),
            "error": str(e),
        }
